version: '3.5'
services:
  app:
      image: cr.gitlab.fhnw.ch/ip34-23vt/ip34-23vt_therewrite/therewrite/frontend:latest
      restart: always
      ports:
          - "80:8080"
          #- "443:8443"
      networks:
        - therewrite
  database:
      container_name: postgresCont
      image: postgres:latest
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: $d^8=815D95<s)*"74?a£:d]s1bN^|ykuke_n7?)vnL!W3Z!8
        POSTGRES_DB: TheRewrite
      volumes:
        - /var/lib/docker/volumes/postgres-volume/_data
      ports:
        - '5432:5432'
      expose:
        - '5432'
      networks:
        - therewrite
networks:
  therewrite:
    name: therewrite
    external: true
    driver: bridge
